replacements: list[tuple[str, str]] = [
    (r"\'e", "é"),
    (r"\^e", "ê"),
    (r"\`e", "è"),
    (r"\"e", "ë"),
    (r"\'a", "('↑a)"),
    (r"\^a", "â"),
    (r"\`a", "à"),
    (r"\"a", "(¨↑a)"),
    (r"\'i", "('↑o)"),
    (r"\^i", "î"),
    (r"\`i", "(`↑i)"),
    (r"\"i", "ï"),
    (r"\'o", "('↑o)"),
    (r"\^o", "ô"),
    (r"\`o", "(`↑o)"),
    (r"\"o", "ö"),
    (r"\'u", "('↑u)"),
    (r"\^u", "û"),
    (r"\`u", "ù"),
    (r"\"u", "ü"),
    (r"\c{c}", "ç"),
    (r"\smallskip", ""),
    (r"\medskip", ""),
    (r"\bigskip", ""),
    (r"\begin{equation}", "$"),
    (r"\begin{equation}", "$"),
    (r"\end{equation}", "$"),
    (r"\begin{equation*}", "$"),
    (r"\end{equation*}", "$"),
    (r"\(", "$"),
    (r"\)", "$"),
    (r"\[", "$"),
    (r"\]", "$"),
    (r"$$", "$"),
    (r"\dots", "..."),
    (r"\quad", ""),
    (r"\colon", ":"),
    (r"\,", " "),
    (r"\;", " "),
    (r"\ ", " "),
    (r"\etale", "étale"),
    (" e0", "à"),
    (" e9", "é"),
    (" f9", "ù"),
    (r"\{\mathcal U\}", r"\mathcal U"),
    (r"\{\mathcal{U}\}", r"\mathcal U"),
    (r"\longrightarrow", r"\to"),
    (r"\rightarrow", r"\to"),
    (r"\Longrightarrow", r"\Rightarrow"),
    (r"\longlefttarrow", r"\leftarrow"),
    (r"\widehat", r"\hat"),
    (r"\left", ""),
    (r"\right", ""),
    (r"\operatorname", r"\mathrm"),
    (r"\mathop", r"\mathrm"),
    ("``", '"'),
    ("''", '"'),
    ("«", '"'),
    ("»", '"'),
    ("O.P.S.", "OPS"),
    ("O.P.S", "OPS"),
    (r"\varprojlim", r"\lim_{\to}"),
    (r"\varinjlim", r"\lim_{\leftarrow}"),
    (r"\ ", ""),
    (r"\,", ""),
    (r"\;", ""),
    (r"\:", ""),
    (r"\quad", ""),
    (r"\qquad", ""),
    ("—", "-"),
    (r"\big", ""),
    (r"\ldots", r"\dots"),
    (r"\/", r""),
    (r"\nobreak", ""),
    ("N.B.", "NB"),
    ("N.B", "NB"),
    ("NB.", "NB"),
    (" ...", "..."),
    (r"\text{catégoriel U}", r"\mathcal{U}"),
    # Regularizaciones de unicode
    ("‑", "-"),
    ("’", "'"),
    ("“", '"'),
    ("”", '"'),
    ("`", "'"),
    ("§", r"\S"),
    ("…", "..."),
    ("–", "-"),
    # Regularización del texto en francés
    ("~", " "),
    ("á", "à"),
    ("ó", "ò"),
]
replacements_envs: list[tuple[str, str]] = [
    # la sintaxis es (apertura, cierre) del entorno, se quita t0do menos lo de dentro
    (r"{\bf", "}"),
    (r"{ \bf", "}"),
    (r"{\it", "}"),
    (r"{ \it", "}"),
    (r"{\sl", "}"),
    (r"{ \sl", "}"),
    (r"{\cal", "}"),
    (r"{ \cal", "}"),
    (r"{\mathcal", "}"),
    (r"{ \mathcal", "}"),
    (r"\textit{", "}"),
    (r"\textbf{", "}"),
    (r"\textsl{", "}"),
    (r"\underline{", "}"),
    (r"\emph{", "}"),
    (r"\emph{donnée}", "donnée"),
    (r"\footnote{", "}"),
    (r"\begin{center}", r"\end{center}"),
]

text_nobracket_p = r"[^{}]"
bracketed_block = r"\{" + text_nobracket_p + r"*\}"
cmm_p = r"\\[a-zA-Z]+"
for _ in range(10):
    # creamos un bloque de contenido entre llaves - el 10 es un número arbitrario, pero parece razonable.
    bracketed_block = r"\{(?:" + text_nobracket_p + r"|" + bracketed_block + r")*\}"
scriptable_block = rf"({cmm_p}|\w|{bracketed_block})"

regex_replacements: list[tuple[str, str]] = [
    # (pattern, replacement)
    # en la parte de replacement solamente se formatean raro las barras invertidas \, que tienen que ir como \\
    # para diferenciarlas de los grupos de captura que se van a sustituir (\1, \2, etc.).
    (
        r"\\n(?!(?:ot|ew|ode|u|eq|exists|ewpage|oindent|atural|eg|earrow|warrow|abla|obreak|otag)(?![a-zA-Z]))",
        " ",
    ),
    # reemplazar nuevas líneas
    (r"\\U\b", r"\\mathcal U"),
    (r"\\E\b", r"\\mathcal E"),
    (r"-{2,}", "-"),
    (r"\s+:", ":"),
    (r"\s+;", ";"),
    (r"\(\s+", r"("),
    (r"\s+\)", r")"),
    (r"\[\s+", r"["),
    (r"\s+\]", r"]"),
    (r"\s+!", "!"),
    (r"\s+\?", "?"),
    (r"\\mathcal\{\s*([a-zA-Z])\s*\}", r"\\mathcal \1"),
    (r"\\mathfrak\{\s*([a-zA-Z])\s*\}", r"\\mathfrak \1"),
    (r"\\mathbb\{\s*([a-zA-Z])\s*\}", r"\\mathbb \1"),
    (rf"\{{\\rm\s+({bracketed_block}|{text_nobracket_p}+)\}}", r"\\mathrm{\1}"),
    (r"\\tag\{\d*\}", ""),
    (r"\\not\s*=", r"\neq"),
    (r"\{\\cal\s*", r"\\mathcal{"),
    (r"\\cal", r"\\mathcal"),
    (r"\{\\frak\s*", r"\\mathfrak{"),
    (r"\\frak", r"\\mathfrak"),
    (rf"\\textrm({bracketed_block})", r"\\text\1"),
    (rf"\\operatorname({bracketed_block})", r"\\text\1"),
    (r"\s{2,}", " "),
    # (rf"\\overset({bracketed_block})({bracketed_block})", r"\2^\1"),
]

task_specific_regex_replacements: dict[int, list[tuple[str, str]]] = {
    438: [
        (r"\{\\ U\\\}", r"{U}"),
    ],
}

french_latex_characters: list[str] = [
    # letras, dígitos
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "ö",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "é",
    "à",
    "è",
    "ù",
    "â",
    "ê",
    "î",
    "ô",
    "û",
    "ë",
    "ï",
    "ü",
    "ÿ",
    "ç",
    "œ",
    "æ",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "É",
    "À",
    "È",
    "Ù",
    "Â",
    "Ê",
    "Î",
    "Ô",
    "Û",
    "Ë",
    "Ï",
    "Ü",
    "Ÿ",
    "Ç",
    "Œ",
    "Æ",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    # control
    " ",
    "\t",
    "\n",
    "\r",
    # puntuación
    ".",
    ",",
    ";",
    ":",
    "!",
    "?",
    "(",
    ")",
    "[",
    "]",
    "{",
    "}",
    "-",
    "_",
    "/",
    "\\",
    "|",
    "@",
    "#",
    "$",
    "%",
    "^",
    "&",
    "*",
    "+",
    "=",
    "<",
    ">",  # '~', '`', '\'', '"',
    # '«', '»', '€'
    "'",
    '"',
]
