replacements = [
    (r"\'e", "é"),
    (r"\^e", "ê"),
    (r"\`e", "è"),
    (r"\"e", "ë"),
    (r"\'a", "á"),
    (r"\^a", "ä"),
    (r"\`a", "à"),
    (r"\"a", "ä"),
    (r"\'i", "í"),
    (r"\^i", "î"),
    (r"\`i", "ì"),
    (r"\"i", "ï"),
    (r"\'o", "ò"),
    (r"\^o", "ô"),
    (r"\`o", "ò"),
    (r"\"o", "ö"),
    (r"\'u", "ú"),
    (r"\^u", "û"),
    (r"\`u", "ù"),
    (r"\"u", "ü"),
    (r"\c{c}", "ç"),
    (r"\smallskip", ""),
    (r"\medskip", ""),
    (r"\bigskip", ""),
    (r"\begin{equation}", "$"),
    (r"\begin{equation}", "$"),
    (r"\end{equation}", "$"),
    (r"\begin{equation*}", "$"),
    (r"\end{equation*}", "$"),
    (r"\(", "$"),
    (r"\)", "$"),
    (r"\[", "$"),
    (r"\]", "$"),
    (r"$$", "$"),
    (r"\dots", "..."),
    (r"\quad", ""),
    (r"\colon", ":"),
    (r"\,", " "),
    (r"\;", " "),
    (r"\ ", " "),
    (r"\etale", "étale"),
    (" e0", "à"),
    (" e9", "é"),
    (" f9", "ù"),
    (r"\{\mathcal U\}", r"\mathcal U"),
    (r"\{\mathcal{U}\}", r"\mathcal U"),
    (r"\longrightarrow", r"\to"),
    (r"\rightarrow", r"\to"),
    (r"\Longrightarrow", r"\Rightarrow"),
    (r"\longlefttarrow", r"\leftarrow"),
    (r"\left", ""),
    (r"\right", ""),
    (r"\operatorname", r"\mathrm"),
    (r"\mathop", r"\mathrm"),
    ("``", '"'),
    ("''", '"'),
    ("«", '"'),
    ("»", '"'),
    ("O.P.S.", "OPS"),
    ("O.P.S", "OPS"),
    (r"\varprojlim", r"\lim_{\to}"),
    (r"\varinjlim", r"\lim_{\leftarrow}"),
    (r"\ ", ""),
    (r"\,", ""),
    (r"\;", ""),
    (r"\:", ""),
    (r"\quad", ""),
    (r"\qquad", ""),
    ("—", "-"),
    (r"\big", ""),
    (r"\ldots", r"\dots"),
    (r"\/", r""),
    (r"\nobreak", ""),
    ("N.B.", "NB"),
    ("N.B", "NB"),
    ("NB.", "NB"),
    (" ...", "..."),
    (r"\cal", r"\mathcal"),
    (r"\frak", r"\mathfrak"),
]
replacements_envs = [
    # la sintaxis es (apertura, cierre) del entorno, se quita t0do menos lo de dentro
    (r"{\bf", "}"),
    (r"{ \bf", "}"),
    (r"{\it", "}"),
    (r"{ \it", "}"),
    (r"{\sl", "}"),
    (r"{ \sl", "}"),
    (r"\textit{", "}"),
    (r"\textbf{", "}"),
    (r"\textsl{", "}"),
    (r"\underline{", "}"),
    (r"\emph{", "}"),
    (r"\emph{donnée}", "donnée"),
    (r"\footnote{", "}"),
    (r"\begin{center}", r"\end{center}"),
]

text_nobracket_p = r"[^{}]"
bracketed_block = r"\{" + text_nobracket_p + r"*\}"
cmm_p = r"\\[a-zA-Z]+"
for _ in range(10):
    # creamos un bloque de contenido entre llaves - el 10 es un número arbitrario, pero parece razonable.
    bracketed_block = r"\{(?:" + text_nobracket_p + r"|" + bracketed_block + r")*\}"
scriptable_block = rf"({cmm_p}|\w|{bracketed_block})"

regex_replacements = [
    # (pattern, replacement)
    # en la parte de replacement solamente se formatean raro las barras invertidas \, que tienen que ir como \\
    # para diferenciarlas de los grupos de captura que se van a sustituir (\1, \2, etc.).
    (
        r"\\n(?!(?:ot|ew|ode|u|eq|exists|ewpage|oindent|atural|eg|earrow|warrow|abla|obreak)(?![a-zA-Z]))",
        " ",
    ),
    # reemplazar nuevas líneas
    (r"\\U\b", r"\\mathcal U"),
    (r"\\E\b", r"\\mathcal E"),
    (r"-{2,}", "-"),
    (r"\s+:", ":"),
    (r"\s+;", ";"),
    (r"\(\s+", r"("),
    (r"\s\)+", r")"),
    (r"\[\s+", r"["),
    (r"\s\]+", r"]"),
    (r"\s+!", "!"),
    (r"\s+\?", "?"),
    (r"\\mathcal\{\s*([a-zA-Z])\s*\}", r"\\mathcal \1"),
    (r"\\mathfrak\{\s*([a-zA-Z])\s*\}", r"\\mathfrak \1"),
    (r"\\mathbb\{\s*([a-zA-Z])\s*\}", r"\\mathbb \1"),
    (rf"\{{\\rm\s+({text_nobracket_p})\}}", r"\\mathrm{\1}"),
    (r"\\tag\{\d*\}", ""),
    (r"\s{2,}", " "),
    # (rf"\\overset({bracketed_block})({bracketed_block})", r"\2^\1"),
]
