replacements = [
    (r"\'e", "é"),
    (r"\^e", "ê"),
    (r"\`e", "è"),
    (r"\"e", "ë"),
    (r"\'a", "á"),
    (r"\^a", "ä"),
    (r"\`a", "à"),
    (r"\"a", "ä"),
    (r"\'i", "í"),
    (r"\^i", "î"),
    (r"\`i", "ì"),
    (r"\"i", "ï"),
    (r"\'o", "ò"),
    (r"\^o", "ô"),
    (r"\`o", "ò"),
    (r"\"o", "ö"),
    (r"\'u", "ú"),
    (r"\^u", "û"),
    (r"\`u", "ù"),
    (r"\"u", "ü"),
    (r"\c{c}", "ç"),
    (r"\smallskip", ""),
    (r"\medskip", ""),
    (r"\bigskip", ""),
    (r"\begin{equation}", "$"),
    (r"\begin{equation}", "$"),
    (r"\end{equation}", "$"),
    (r"\begin{equation*}", "$"),
    (r"\end{equation*}", "$"),
    (r"\(", "$"),
    (r"\)", "$"),
    (r"\[", "$"),
    (r"\]", "$"),
    (r"$$", "$"),
    (r"\dots", "..."),
    (r"\quad", ""),
    (r"\colon", ":"),
    (r"\,", " "),
    (r"\;", " "),
    (r"\ ", " "),
    (r"\etale", "étale"),
    (" e0", "à"),
    (" e9", "é"),
    (" f9", "ù"),
    (r"\{\mathcal U\}", r"\mathcal U"),
    (r"\{\mathcal{U}\}", r"\mathcal U"),
]
replacements_envs = [
    # la sintaxis es (apertura, cierre) del entorno, se quita t0do menos lo de dentro
    (r"{\bf", "}"),
    (r"{ \bf", "}"),
    (r"{\it", "}"),
    (r"{ \it", "}"),
    (r"{\sl", "}"),
    (r"{ \sl", "}"),
    (r"\textit{", "}"),
    (r"\textbf{", "}"),
    (r"\textsl{", "}"),
    (r"\underline{", "}"),
    (r"\emph{", "}"),
    (r"\footnote{", "}"),
    (r"\begin{center}", r"\end{center}"),
    (r"\tag{", "}"),
]

regex_replacements = [
    (
        r"\\n(?!(?:ot|ew|ode|u|eq|exists|ewpage|oindent|natural|eg|earrow|warrow|abla)\b)",
        " ",
    ),
    # reemplazar nuevas líneas
    (r"\\U\b", r"\\mathcal U"),
    (r"\\E\b", r"\\mathcal E"),
]
